account/urls.py
from django.urls import path
from account import views

app_name = 'account'
urlpatterns = [
    path('login', views.UserLoginView.as_view(), name='user login'),
    path('register', views.OtpLoginView.as_view(), name='user register'),
    path('checkotp', views.CheckOtpView.as_view(), name='check otp'),
    path('logout', views.user_logout, name='log out'),
    path('edit', views.edit_profile, name='Edit profile'),
    path('add/address', views.AddAddressView.as_view(), name='add_address'),
    # path('edit', views.EditProfileView.as_view(), name='Edit profile'),

]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('detail', views.CartDetailView.as_view(), name='cart_detail'),
    path('add/<int:pk>', views.CartAddView.as_view(), name='cart_add'),
    path('remove/<str:id>', views.CartDeleteView.as_view(), name='remove'),
    path('order/<int:pk>', views.OrderDetailView.as_view(), name='order_detail'),
    path('order/add', views.OrderCreationView.as_view(), name='order_creation'),
    path('applydis/<int:pk>', views.ApplyDiscountView.as_view(), name='apply_dis'),
    path('sendrequest/<int:pk>', views.SendRequestView.as_view(), name='send_request'),
    path('verify/', views.VerifyView.as_view(), name='verify'),
]

djangoProject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from djangoProject import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include("account.urls")),
    path('', include("home.urls")),
    path('products/', include("product.urls")),
    path('cart/', include("cart.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views
from .views import send_message

urlpatterns = [
    path('', views.Home.as_view(), name='main'),
    path('contactus', send_message, name='contactus'),

]

product/urls.py
from django.urls import path
from . import views
from .views import NavbarPartialView, CategoryPartialView, FeaturedProductsPartialView, RecentProductsPartialView, \
    OfferPartialView, OfferBrand, BrandePartialView, LikedProductsPartialView, LikedProductsCountView

app_name = "product"
urlpatterns = [
    path('all', views.ProductListView.as_view(), name='product_list'),
    path('search', views.search, name='search'),
    path('<int:pk>', views.ProductDetailView.as_view(), name='product_detail'),# az inja bayad benevisam havaset bashe vaseye category list
    # path('feature/<int:pk>', views.FeatureProductDetailView.as_view(), name='feature_detail'),# az inja bayad benevisam havaset bashe vaseye category list
    path('navbar', NavbarPartialView.as_view(), name='navbar'),
    path('Cat', CategoryPartialView.as_view(), name='cat'),
    path('Feature', FeaturedProductsPartialView.as_view(), name='Feature'),
    path('category/<slug:category_slug>/', views.product_list_category, name='product_list_by_category'),
    path('recent', RecentProductsPartialView.as_view(), name='recent'),
    path('offer', OfferPartialView.as_view(), name='offer'),
    path('offer_brand', OfferBrand.as_view(), name='offer_brand'),
    path('brande', BrandePartialView.as_view(), name='brande'),
    path('liked-products-count', LikedProductsCountView.as_view(), name='liked-products-count'),
    path('ob', LikedProductsPartialView.as_view(), name='liked-products'),
    path('like/<slug:slug>/<int:pk>', views.like, name='like'),
]

home/models.py
from django.db import models
from django.contrib.auth.models import User  # وارد کردن مدل کاربر
from django.conf import settings


class Message(models.Model):
    sender = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    email = models.EmailField()
    subject = models.CharField(max_length=100)
    message = models.TextField(verbose_name='Message')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد")

    def __str__(self):
        return self.sender.username

    class Meta:
        verbose_name = "پیام"
        verbose_name_plural = "پیام‌ها"

product/models.py
from autoslug.settings import slugify
from django.db import models
from django.db.models import ExpressionWrapper, Count


from account.models import User


class Size(models.Model):
    title = models.CharField(max_length=10)

    def __str__(self):
        return self.title


class Color(models.Model):
    title = models.CharField(max_length=10)

    def __str__(self):
        return self.title


class Category(models.Model):
    parent = models.ForeignKey('self', blank=True, null=True, related_name='subs', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='category/images', blank=True, null=True)
    title = models.CharField(max_length=50)
    slug = models.SlugField()

    def __str__(self):
        return self.title


class Type(models.Model):
    title = models.CharField(max_length=30)

    def __str__(self):
        return self.title


class Product(models.Model):
    title = models.CharField(max_length=30)
    slug = models.SlugField(unique=True, blank=True)
    description = models.TextField()
    price = models.IntegerField()
    discount = models.SmallIntegerField()
    size = models.ManyToManyField(Size, related_name='products', blank=True, null=True)
    color = models.ManyToManyField(Color, related_name='products', blank=True, null=True)
    type = models.ManyToManyField(Type, related_name="products", blank=True, null=True)
    category = models.ManyToManyField(Category, related_name='products', blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_comment_count(self):
        return self.comments.annotate(reply_count=Count('replys')).count()

    # class Meta:
    #     ordering = ('-created',)


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to='product_images/')  # آدرس ذخیره‌سازی تصاویر

    def __str__(self):
        return f"Image for {self.product.title}"


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='likes', verbose_name='کاربر')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='likes', verbose_name='محصول')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username}-{self.product.title}"

    class Meta:
        verbose_name = 'لایک'
        verbose_name_plural = 'لایک ها'
        ordering = ('-created_at',)


class OrderItem(models.Model):
    item = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"order of {self.item.title}"

    def get_total_item_price(self):
        """calculate price by quantity ,ex 4 phone of 100$ would be 400$ """
        return self.quantity * self.item.price

    def get_item_price_after_discount(self):
        """calculate price with discount ,ex 1 phone of 100$ with 25% would be 100*0.25 = 75$ """
        return self.item.price * self.item.discount

    def get_total_discount_item_price(self):
        """calculate price by quantity with discount ,ex 4 phone of 100$ with 25% would be 400*0.25 = 300$ """
        return self.quantity * self.get_item_price_after_discount()

    def get_difference_price_after_discount(self):
        """,ex 4 phone of 100$ with 25% would be (400$ - 400*0.25 = 100$) """
        return self.get_total_item_price() - self.get_total_discount_item_price()


class Information(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="information", null=True, blank=True)
    text = models.TextField()

    def __str__(self):
        return self.text[:30]


class FeaturedProducts(models.Model):
    image = models.ImageField(blank=True, null=True, upload_to='FeaturedProducts/images')
    title = models.CharField(max_length=50, blank=True, null=True)
    price = models.FloatField()
    slug = models.SlugField()
    description = models.TextField()
    discount = models.SmallIntegerField()
    size = models.ManyToManyField(Size, related_name='fproducts', blank=True, null=True)
    color = models.ManyToManyField(Color, related_name='fproducts', blank=True, null=True)
    type = models.ManyToManyField(Type, related_name="fproducts", blank=True, null=True)

    def __str__(self):
        return self.title


class OfferProducts(models.Model):
    product = models.ForeignKey(Product, blank=True, null=True, on_delete=models.CASCADE, related_name='products')
    image = models.ImageField(upload_to='offer/image')
    price = models.IntegerField()
    discount = models.IntegerField()

    @property
    def total_price(self):
        return int(self.price - (self.price * self.discount / 100))

    def __str__(self):
        if self.product:
            return self.product.title
        return f"Offer #{self.id}"


class Brande(models.Model):
    brande = models.CharField(max_length=30, blank=True, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, blank=True, null=True)
    image = models.ImageField(upload_to='image/brande')

    def __str__(self):
        return self.brande


class Comments(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, blank=True, null=True, related_name='comments')
    parent = models.ForeignKey('self', on_delete=models.CASCADE, related_name='replys', blank=True, null=True,
                               default=None)

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments', null=True, blank=True)
    body = models.TextField(max_length=500)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.body[:50]

home/forms.py
from django import forms

from home.models import Message


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['email', 'subject', 'message']  # فقط فیلد پیام نمایش داده می‌شود

home/views.py
from django.views import View
from django.views.generic import TemplateView, ListView
from django.shortcuts import render, redirect

from product.models import Category
from .forms import MessageForm


class Home(TemplateView):
    template_name = "base.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        print(self.request.session.get('myname', 'sajjad'))
        return context


def send_message(request):
    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            form.instance.sender = request.user  # اختصاص مقدار ارسال‌کننده
            form.save()
            return redirect('main')  # یا به هر صفحه دیگری که می‌خواهید منتقل شوید
    else:
        form = MessageForm()
    return render(request, 'contactUs.html', {'form': form})

product/views.py
from msilib.schema import ListView

from django.contrib.auth.decorators import login_required
from django.views.generic import DetailView, TemplateView
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator
from product.models import Product, OrderItem, Category, FeaturedProducts, Like, OfferProducts, Brande



class ProductDetailView(DetailView):
    template_name = 'product/detail1.html'
    model = Product

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data()
        if self.request.user.is_authenticated:  # بررسی احراز هویت کاربر
            if self.request.user.likes.filter(product__slug=self.object.slug).exists():
                context['is_liked'] = True
            else:
                context['is_liked'] = False
        else:

            context['is_liked'] = False  # در صورتی که کاربر وارد نشده باشد، ایس_لایک را به False تنظیم کنید
        return context


def order_item_list(request):
    order_items = OrderItem.objects.all()
    return render(request, 'product/detail1.html', {'order_items': order_items})


class NavbarPartialView(TemplateView):
    template_name = 'home/include/nav_bar.html'

    def get_context_data(self, **kwargs):
        context = super(NavbarPartialView, self).get_context_data()
        context['categories'] = Category.objects.all()
        return context


class ProductListView(TemplateView):
    template_name = 'products_list.html'

    def get_context_data(self, **kwargs):
        request = self.request
        context = super().get_context_data(**kwargs)
        # form = ProductFilterForm(self.request.GET)
        sort_by = self.request.GET.get('sort')
        show_count = self.request.GET.get('show')

        queryset = Product.objects.all()

        if sort_by == 'latest':
            queryset = queryset.order_by('-created_at')
        elif sort_by == 'best_rating':
            queryset = queryset.order_by('likes')

        if show_count:
            paginator = Paginator(queryset, int(show_count))
        else:
            paginator = Paginator(queryset, 3)

        page_number = self.request.GET.get('page')
        object_list = paginator.get_page(page_number)
        context['object_list'] = object_list

        # context['form'] = form
        return context


class CategoryPartialView(TemplateView):
    template_name = 'home/include/category.html'

    def get_context_data(self, **kwargs):
        context = super(CategoryPartialView, self).get_context_data()
        context['category_object'] = Category.objects.all()
        return context


class FeaturedProductsPartialView(TemplateView):
    template_name = 'home/include/product.html'
    model = FeaturedProducts

    def get_context_data(self, **kwargs):
        queryset = FeaturedProducts.objects.all()
        context = super(FeaturedProductsPartialView, self).get_context_data()
        context['feature'] = queryset
        return context


class RecentProductsPartialView(TemplateView):
    template_name = 'home/include/products_list.html'
    queryset = Product.objects.all()

    def get_context_data(self, **kwargs):
        request = self.request
        queryset = Product.objects.all().order_by('-created_at')[:4]
        context = super(RecentProductsPartialView, self).get_context_data()
        context['recent'] = queryset
        return context


def like(request, pk, slug):
    if request.user.is_authenticated:
        try:
            like = Like.objects.get(product__slug=slug, user_id=request.user.id)
            like.delete()
        except Like.DoesNotExist:
            Like.objects.create(product_id=pk, user_id=request.user.id)

        # پس از لایک یا آنلایک، کاربر را به صفحه محصول هدایت کنید.
        return redirect('product:product_detail', pk=pk)


class OfferPartialView(TemplateView):
    template_name = 'home/include/offer.html'
    queryset = OfferProducts.objects.all()

    def get_context_data(self, **kwargs):
        request = self.request
        queryset = OfferProducts.objects.all()
        context = super(OfferPartialView, self).get_context_data()
        context['offer'] = queryset
        return context


class OfferBrand(TemplateView):
    template_name = 'home/include/carousel.html'
    queryset = OfferProducts.objects.all()

    def get_context_data(self, **kwargs):
        request = self.request
        queryset = OfferProducts.objects.all()
        context = super(OfferBrand, self).get_context_data()
        context['offer_brand'] = queryset
        return context


class BrandePartialView(TemplateView):
    template_name = 'home/include/vendor.html'
    queryset = Brande.objects.all()

    def get_context_data(self, **kwargs):
        request = self.request
        queryset = Brande.objects.all()
        context = super(BrandePartialView, self).get_context_data()
        context['all_brand'] = queryset
        return context


@login_required
def liked_products_count_view(request):
    liked_product_count = Like.objects.filter(user=request.user).count()
    return render(request, 'home/include/nav_bar.html', {'liked_product_count': liked_product_count})


class LikedProductsPartialView(TemplateView):
    model = Like
    template_name = 'home/include/liked.html'  # نام تمپلیت مورد استفاده

    def get_context_data(self, **kwargs):
        request = self.request
        queryset = Like.objects.all()
        context = super(LikedProductsPartialView, self).get_context_data()
        context['all_like'] = queryset
        return context


class LikedProductsCountView(TemplateView):
    template_name = 'home/include/nav_bar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        liked_product_count = Like.objects.filter(user=self.request.user).count()
        context['liked_product_count'] = liked_product_count
        return context


def search(request):
    q = request.GET.get('q')
    product = Product.objects.filter(title__icontains=q)
    return render(request, 'products_list.html', context={'object_list': product})


def product_list_category(request, category_slug):
    category = Category.objects.filter(slug=category_slug).first()

    products = category.products.all()

    return render(request, 'home/include/cat_list.html', {'cat_list': products})

home/templates/home/include/category.html
{% load static %}


<div class="container-fluid pt-5">
    <h2 class="section-title position-relative text-uppercase mx-xl-5 mb-4"><span class="bg-secondary pr-3">Categories</span></h2>
    <div class="row px-xl-5 pb-3">
{% for cat in category_object %}
        <div class="col-lg-3 col-md-4 col-sm-6 pb-1">
            <a class="text-decoration-none" href="{% url 'product:product_list_by_category' cat.slug %}">
                <div class="cat-item d-flex align-items-center mb-4">
                    <div class="overflow-hidden" style="width: 100px; height: 100px;">
                        <img class="img-fluid" src="{{ cat.image.url }}" alt="{{ 'hi' }}">
                    </div>
                    <div class="flex-fill pl-3">
                        <h6>{{ cat.title }}</h6>
{#                        <small class="text-body">{{ cat.subs.count }} Subcategories</small>#}
                    </div>
                </div>
            </a>
        </div>
{% endfor %}
    </div>
</div>

home/templates/home/include/footer.html
{% load static %}
{% load social_share %}
<div class="container-fluid bg-dark text-secondary mt-5 pt-5">
    <div class="row px-xl-5 pt-5">
        <div class="col-lg-4 col-md-12 mb-5 pr-3 pr-xl-5">
            <h5 class="text-secondary text-uppercase mb-4">Get In Touch</h5>
            <p class="mb-4">No dolore ipsum accusam no lorem. Invidunt sed clita kasd clita et et dolor sed dolor. Rebum
                tempor no vero est magna amet no</p>
            <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>au/sydney</p>
            <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>sajjad.aziziant@yahoo.com</p>
            <p class="mb-0"><i class="fa fa-phone-alt text-primary mr-3"></i>+989134523580</p>
        </div>
        <div class="col-lg-8 col-md-12">
            <div class="row">
                <div class="col-md-4 mb-5">
                    <h5 class="text-secondary text-uppercase mb-4">Quick Shop</h5>
                    <div class="d-flex flex-column justify-content-start">
                        <a class="text-secondary mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Home</a>
                        <a class="text-secondary mb-2" href="{% url 'product:product_list' %}"><i
                                class="fa fa-angle-right mr-2"></i>Shop Detail</a>
                        <a class="text-secondary" href="{% url 'contactus' %}"><i class="fa fa-angle-right mr-2"></i>Contact
                            Us</a>
                    </div>
                </div>
                <div class="col-md-4 mb-5">
                    <h5 class="text-secondary text-uppercase mb-4">My Account</h5>
                    <div class="d-flex flex-column justify-content-start">
                        <a class="text-secondary mb-2" href="{% url 'account:Edit profile' %}"><i
                                class="fa fa-angle-right mr-2"></i>Profile</a>
                        <a class="text-secondary mb-2" href="{% url 'account:add_address' %}"><i
                                class="fa fa-angle-right mr-2"></i>Address</a>

                    </div>
                </div>

                <div class="d-flex">
                    <a class="btn btn-primary btn-square" href="https://www.instagram.com/troshopp/"><i class="fab fa-instagram"></i></a>



                </div>
            </div>
        </div>
    </div>
</div>
<center>
    <div class="row border-top mx-xl-5 py-4" style="border-color: rgba(256, 256, 256, .1) !important;">

        <div class="col-md-6 px-xl-0 text-center text-md-right">
            <img class="img-fluid" src="{% static 'img/payments.png' %}" alt="">
        </div>
    </div>
</center>
</div>

home/templates/home/include/head.html
{% load static %}
<meta charset="utf-8">
    <title>MultiShop - Online Shop Website Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Favicon -->
    <link href="{% static 'img/favicon.ico' %}" rel="icon">


    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

home/templates/home/include/nav_bar.html
{% load static %}
<div class="container-fluid bg-dark mb-30">
    <div class="row px-xl-5">
{#        <div class="col-lg-3 d-none d-lg-block">#}
{#            <a class="btn d-flex align-items-center justify-content-between bg-primary w-100" data-toggle="collapse"#}
{#               href="#navbar-vertical" style="height: 65px; padding: 0 30px;">#}
{#                <h6 class="text-dark m-0"><i class="fa fa-bars mr-2"></i>Categories</h6>#}
{#                <i class="fa fa-angle-down text-dark"></i>#}
{#            </a>#}
{#            <nav class="collapse position-absolute navbar navbar-vertical navbar-light align-items-start p-0 bg-light"#}
{#                 id="navbar-vertical" style="width: calc(100% - 30px); z-index: 999;">#}
{#                <div class="navbar-nav w-100">#}
{#                    {% for category in categories %}#}
{#                        {% if not category.parent %}#}
{#                            {% if category.subs.all %}#}
{#                                <div class="nav-item dropdown dropright">#}
{#                                    <a href="#" class="nav-link dropdown-toggle"#}
{#                                       data-toggle="dropdown">{{ category.title }} <i#}
{#                                            class="fa fa-angle-right float-right mt-1"></i></a>#}
{#                                    <div class="dropdown-menu position-absolute rounded-0 border-0 m-0">#}
{#                                        {% for sub in category.subs.all %}#}
{#                                            <a href="" class="dropdown-item">{{ sub.title }}</a>#}
{#                                        {% endfor %}#}
{##}
{#                                    </div>#}
{#                                </div>#}
{#                            {% else %}#}
{#                                <a href="" class="nav-item nav-link">{{ category.title }}</a>#}
{#                            {% endif %}#}
{#                        {% endif %}#}
{#                    {% endfor %}#}
{##}
{#                </div>#}
{#            </nav>#}
{#        </div>#}
        <div class="col-lg-9">
            <nav class="navbar navbar-expand-lg bg-dark navbar-dark py-3 py-lg-0 px-0">
                <a href="" class="text-decoration-none d-block d-lg-none">
                    <span class="h1 text-uppercase text-dark bg-light px-2">Multi</span>
                    <span class="h1 text-uppercase text-light bg-primary px-2 ml-n1">Shop</span>
                </a>
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                    <div class="navbar-nav mr-auto py-0">
                        <a href="{% url 'main' %}" class="nav-item nav-link active">Home</a>
                        <a href="{% url 'product:product_list' %}" class="nav-item nav-link">Shop</a>
                        <div class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Pages <i
                                    class="fa fa-angle-down mt-1"></i></a>
                            <div class="dropdown-menu bg-primary rounded-0 border-0 m-0">
                                <a href="{% url 'cart:order_creation' %}" class="dropdown-item">Shopping Cart</a>

                                <a href="" class="dropdown-item">Checkout</a>
                            </div>
                        </div>
                        <a href="{% url 'contactus' %}" class="nav-item nav-link">Contact</a>

                    </div>
                    <div class="navbar-nav ml-auto d-none d-lg-block">
                        <a href="{% url 'product:liked-products' %}" class="btn px-0" id="liked-products-count">
                            <i class="fas fa-heart text-primary"></i>
                            <span class="badge text-secondary border border-secondary rounded-circle"
                                  style="padding-bottom: 2px;">{{ liked_product_count }}</span>
                        </a>
                        <a href="{% url 'cart:cart_detail' %}" class="btn px-0 ml-3">
                            <i class="fas fa-shopping-cart text-primary"></i>
                            <span class="badge text-secondary border border-secondary rounded-circle"
                                  style="padding-bottom: 2px;"></span>
                        </a>
                    </div>


                    <div id="liked-products-list">
                        <!-- اینجا لیست محصولات لایک شده نمایش داده خواهد شد -->
                    </div>


                </div>
            </nav>
        </div>
    </div>
</div>

home/templates/home/include/offer.html
{% load static %}
<div class="container-fluid pt-5 pb-3">
    <div class="row px-xl-5">
        {% for item in offer %}
        <div class="col-md-6">
            <div class="product-offer mb-30" style="height: 300px;">
                <img class="img-fluid" src="{{ item.image.url }}" alt="">
                <div class="offer-text">
                    <h6 class="text-white text-uppercase">Save {{ item.discount }}%</h6>
                    <h3 class="text-white mb-3">{{ item.product.title }}</h3>
                    <a href="{% url "cart:cart_add" item.product_id %}" class="btn btn-primary">Shop Now</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

home/templates/home/include/top_bar.html
{% load static %}
<div class="container-fluid">
    <div class="row bg-secondary py-1 px-xl-5">
        <div class="col-lg-6 d-none d-lg-block">
            <div class="d-inline-flex align-items-center h-100">
                <a class="text-body mr-3" href="">About</a>
                <a class="text-body mr-3" href="{% url 'contactus' %}">Contact</a>
                <a class="text-body mr-3" href="">Help</a>
                <a class="text-body mr-3" href="">FAQs</a>
            </div>
        </div>
        <div class="col-lg-6 text-center text-lg-right">
            <div class="d-inline-flex align-items-center">
                <div class="btn-group">
                    <a type="button" class="btn btn-sm btn-light dropdown-toggle" data-toggle="dropdown">My Account</a>
                    <div class="dropdown-menu dropdown-menu-right">
                        {% if request.user.is_authenticated %}
                            <a class="dropdown-item" type="button" href="{% url 'account:Edit profile' %}">Profile</a>
                            <a class="dropdown-item" type="button" href="{% url 'account:log out' %}">Log Out</a>
                        {% else %}
                            <a class="dropdown-item" type="button" href="{% url 'account:user login' %}">Sign in</a>
                            <a class="dropdown-item" type="button" href="{% url 'account:user register' %}">Sign up</a>
                        {% endif %}

                    </div>
                </div>
            </div>
            <div class="d-inline-flex align-items-center d-block d-lg-none">
                <a href="" class="btn px-0 ml-2">
                    <i class="fas fa-heart text-dark"></i>
                    <span class="badge text-dark border border-dark rounded-circle"
                          style="padding-bottom: 2px;">0</span>
                </a>
                <a href="" class="btn px-0 ml-2">
                    <i class="fas fa-shopping-cart text-dark"></i>
                    <span class="badge text-dark border border-dark rounded-circle"
                          style="padding-bottom: 2px;">0</span>
                </a>
            </div>
        </div>
    </div>
    <div class="row align-items-center bg-light py-3 px-xl-5 d-none d-lg-flex">
        <div class="col-lg-4">
            <a href="" class="text-decoration-none">
                <span class="h1 text-uppercase text-primary bg-dark px-2">Multi</span>
                <span class="h1 text-uppercase text-dark bg-primary px-2 ml-n1">Shop</span>
            </a>
        </div>
        <div class="col-lg-4 col-6 text-left">
            <form action="{% url 'product:search' %}" id="search-form" method="get" name="g">
                <div class="input-group">
                    <input type="text" name="q" class="form-control" placeholder="Search for products"
                           autocomplete="on">
                    <div class="input-group-append">
 <span class="input-group-text bg-transparent text-primary" id="search-icon">
     <i class="fa fa-search"></i>
            </span>
                    </div>
                </div>
            </form>

        </div>
        <div class="col-lg-4 col-6 text-right">
            <p class="m-0">Customer Service</p>
            <h5 class="m-0">+989134523580</h5>
        </div>
    </div>
</div>