cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('detail', views.CartDetailView.as_view(), name='cart_detail'),
    path('add/<int:pk>', views.CartAddView.as_view(), name='cart_add'),
    path('remove/<str:id>', views.CartDeleteView.as_view(), name='remove'),
    path('order/<int:pk>', views.OrderDetailView.as_view(), name='order_detail'),
    path('order/add', views.OrderCreationView.as_view(), name='order_creation'),
    path('applydis/<int:pk>', views.ApplyDiscountView.as_view(), name='apply_dis'),
    path('sendrequest/<int:pk>', views.SendRequestView.as_view(), name='send_request'),
    path('verify/', views.VerifyView.as_view(), name='verify'),
]

djangoProject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from djangoProject import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include("account.urls")),
    path('', include("home.urls")),
    path('products/', include("product.urls")),
    path('cart/', include("cart.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from . import views
from .views import NavbarPartialView, CategoryPartialView, FeaturedProductsPartialView, RecentProductsPartialView, \
    OfferPartialView, OfferBrand, BrandePartialView, LikedProductsPartialView, LikedProductsCountView

app_name = "product"
urlpatterns = [
    path('all', views.ProductListView.as_view(), name='product_list'),
    path('search', views.search, name='search'),
    path('<int:pk>', views.ProductDetailView.as_view(), name='product_detail'),# az inja bayad benevisam havaset bashe vaseye category list
    # path('feature/<int:pk>', views.FeatureProductDetailView.as_view(), name='feature_detail'),# az inja bayad benevisam havaset bashe vaseye category list
    path('navbar', NavbarPartialView.as_view(), name='navbar'),
    path('Cat', CategoryPartialView.as_view(), name='cat'),
    path('Feature', FeaturedProductsPartialView.as_view(), name='Feature'),
    path('category/<slug:category_slug>/', views.product_list_category, name='product_list_by_category'),
    path('recent', RecentProductsPartialView.as_view(), name='recent'),
    path('offer', OfferPartialView.as_view(), name='offer'),
    path('offer_brand', OfferBrand.as_view(), name='offer_brand'),
    path('brande', BrandePartialView.as_view(), name='brande'),
    path('liked-products-count', LikedProductsCountView.as_view(), name='liked-products-count'),
    path('ob', LikedProductsPartialView.as_view(), name='liked-products'),
    path('like/<slug:slug>/<int:pk>', views.like, name='like'),
]

product/models.py
from autoslug.settings import slugify
from django.db import models
from django.db.models import ExpressionWrapper, Count


from account.models import User


class Size(models.Model):
    title = models.CharField(max_length=10)

    def __str__(self):
        return self.title


class Color(models.Model):
    title = models.CharField(max_length=10)

    def __str__(self):
        return self.title


class Category(models.Model):
    parent = models.ForeignKey('self', blank=True, null=True, related_name='subs', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='category/images', blank=True, null=True)
    title = models.CharField(max_length=50)
    slug = models.SlugField()

    def __str__(self):
        return self.title


class Type(models.Model):
    title = models.CharField(max_length=30)

    def __str__(self):
        return self.title


class Product(models.Model):
    title = models.CharField(max_length=30)
    slug = models.SlugField(unique=True, blank=True)
    description = models.TextField()
    price = models.IntegerField()
    discount = models.SmallIntegerField()
    size = models.ManyToManyField(Size, related_name='products', blank=True, null=True)
    color = models.ManyToManyField(Color, related_name='products', blank=True, null=True)
    type = models.ManyToManyField(Type, related_name="products", blank=True, null=True)
    category = models.ManyToManyField(Category, related_name='products', blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_comment_count(self):
        return self.comments.annotate(reply_count=Count('replys')).count()

    # class Meta:
    #     ordering = ('-created',)


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to='product_images/')  # آدرس ذخیره‌سازی تصاویر

    def __str__(self):
        return f"Image for {self.product.title}"


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='likes', verbose_name='کاربر')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='likes', verbose_name='محصول')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username}-{self.product.title}"

    class Meta:
        verbose_name = 'لایک'
        verbose_name_plural = 'لایک ها'
        ordering = ('-created_at',)


class OrderItem(models.Model):
    item = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"order of {self.item.title}"

    def get_total_item_price(self):
        """calculate price by quantity ,ex 4 phone of 100$ would be 400$ """
        return self.quantity * self.item.price

    def get_item_price_after_discount(self):
        """calculate price with discount ,ex 1 phone of 100$ with 25% would be 100*0.25 = 75$ """
        return self.item.price * self.item.discount

    def get_total_discount_item_price(self):
        """calculate price by quantity with discount ,ex 4 phone of 100$ with 25% would be 400*0.25 = 300$ """
        return self.quantity * self.get_item_price_after_discount()

    def get_difference_price_after_discount(self):
        """,ex 4 phone of 100$ with 25% would be (400$ - 400*0.25 = 100$) """
        return self.get_total_item_price() - self.get_total_discount_item_price()


class Information(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="information", null=True, blank=True)
    text = models.TextField()

    def __str__(self):
        return self.text[:30]


class FeaturedProducts(models.Model):
    image = models.ImageField(blank=True, null=True, upload_to='FeaturedProducts/images')
    title = models.CharField(max_length=50, blank=True, null=True)
    price = models.FloatField()
    slug = models.SlugField()
    description = models.TextField()
    discount = models.SmallIntegerField()
    size = models.ManyToManyField(Size, related_name='fproducts', blank=True, null=True)
    color = models.ManyToManyField(Color, related_name='fproducts', blank=True, null=True)
    type = models.ManyToManyField(Type, related_name="fproducts", blank=True, null=True)

    def __str__(self):
        return self.title


class OfferProducts(models.Model):
    product = models.ForeignKey(Product, blank=True, null=True, on_delete=models.CASCADE, related_name='products')
    image = models.ImageField(upload_to='offer/image')
    price = models.IntegerField()
    discount = models.IntegerField()

    @property
    def total_price(self):
        return int(self.price - (self.price * self.discount / 100))

    def __str__(self):
        if self.product:
            return self.product.title
        return f"Offer #{self.id}"


class Brande(models.Model):
    brande = models.CharField(max_length=30, blank=True, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, blank=True, null=True)
    image = models.ImageField(upload_to='image/brande')

    def __str__(self):
        return self.brande


class Comments(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, blank=True, null=True, related_name='comments')
    parent = models.ForeignKey('self', on_delete=models.CASCADE, related_name='replys', blank=True, null=True,
                               default=None)

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments', null=True, blank=True)
    body = models.TextField(max_length=500)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.body[:50]

product/views.py
from msilib.schema import ListView

from django.contrib.auth.decorators import login_required
from django.views.generic import DetailView, TemplateView
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator
from product.models import Product, OrderItem, Category, FeaturedProducts, Like, OfferProducts, Brande



class ProductDetailView(DetailView):
    template_name = 'product/detail1.html'
    model = Product

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data()
        if self.request.user.is_authenticated:  # بررسی احراز هویت کاربر
            if self.request.user.likes.filter(product__slug=self.object.slug).exists():
                context['is_liked'] = True
            else:
                context['is_liked'] = False
        else:

            context['is_liked'] = False  # در صورتی که کاربر وارد نشده باشد، ایس_لایک را به False تنظیم کنید
        return context


def order_item_list(request):
    order_items = OrderItem.objects.all()
    return render(request, 'product/detail1.html', {'order_items': order_items})


class NavbarPartialView(TemplateView):
    template_name = 'home/include/nav_bar.html'

    def get_context_data(self, **kwargs):
        context = super(NavbarPartialView, self).get_context_data()
        context['categories'] = Category.objects.all()
        return context


class ProductListView(TemplateView):
    template_name = 'products_list.html'

    def get_context_data(self, **kwargs):
        request = self.request
        context = super().get_context_data(**kwargs)
        # form = ProductFilterForm(self.request.GET)
        sort_by = self.request.GET.get('sort')
        show_count = self.request.GET.get('show')

        queryset = Product.objects.all()

        if sort_by == 'latest':
            queryset = queryset.order_by('-created_at')
        elif sort_by == 'best_rating':
            queryset = queryset.order_by('likes')

        if show_count:
            paginator = Paginator(queryset, int(show_count))
        else:
            paginator = Paginator(queryset, 3)

        page_number = self.request.GET.get('page')
        object_list = paginator.get_page(page_number)
        context['object_list'] = object_list

        # context['form'] = form
        return context


class CategoryPartialView(TemplateView):
    template_name = 'home/include/category.html'

    def get_context_data(self, **kwargs):
        context = super(CategoryPartialView, self).get_context_data()
        context['category_object'] = Category.objects.all()
        return context


class FeaturedProductsPartialView(TemplateView):
    template_name = 'home/include/product.html'
    model = FeaturedProducts

    def get_context_data(self, **kwargs):
        queryset = FeaturedProducts.objects.all()
        context = super(FeaturedProductsPartialView, self).get_context_data()
        context['feature'] = queryset
        return context


class RecentProductsPartialView(TemplateView):
    template_name = 'home/include/products_list.html'
    queryset = Product.objects.all()

    def get_context_data(self, **kwargs):
        request = self.request
        queryset = Product.objects.all().order_by('-created_at')[:4]
        context = super(RecentProductsPartialView, self).get_context_data()
        context['recent'] = queryset
        return context


def like(request, pk, slug):
    if request.user.is_authenticated:
        try:
            like = Like.objects.get(product__slug=slug, user_id=request.user.id)
            like.delete()
        except Like.DoesNotExist:
            Like.objects.create(product_id=pk, user_id=request.user.id)

        # پس از لایک یا آنلایک، کاربر را به صفحه محصول هدایت کنید.
        return redirect('product:product_detail', pk=pk)


class OfferPartialView(TemplateView):
    template_name = 'home/include/offer.html'
    queryset = OfferProducts.objects.all()

    def get_context_data(self, **kwargs):
        request = self.request
        queryset = OfferProducts.objects.all()
        context = super(OfferPartialView, self).get_context_data()
        context['offer'] = queryset
        return context


class OfferBrand(TemplateView):
    template_name = 'home/include/carousel.html'
    queryset = OfferProducts.objects.all()

    def get_context_data(self, **kwargs):
        request = self.request
        queryset = OfferProducts.objects.all()
        context = super(OfferBrand, self).get_context_data()
        context['offer_brand'] = queryset
        return context


class BrandePartialView(TemplateView):
    template_name = 'home/include/vendor.html'
    queryset = Brande.objects.all()

    def get_context_data(self, **kwargs):
        request = self.request
        queryset = Brande.objects.all()
        context = super(BrandePartialView, self).get_context_data()
        context['all_brand'] = queryset
        return context


@login_required
def liked_products_count_view(request):
    liked_product_count = Like.objects.filter(user=request.user).count()
    return render(request, 'home/include/nav_bar.html', {'liked_product_count': liked_product_count})


class LikedProductsPartialView(TemplateView):
    model = Like
    template_name = 'home/include/liked.html'  # نام تمپلیت مورد استفاده

    def get_context_data(self, **kwargs):
        request = self.request
        queryset = Like.objects.all()
        context = super(LikedProductsPartialView, self).get_context_data()
        context['all_like'] = queryset
        return context


class LikedProductsCountView(TemplateView):
    template_name = 'home/include/nav_bar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        liked_product_count = Like.objects.filter(user=self.request.user).count()
        context['liked_product_count'] = liked_product_count
        return context


def search(request):
    q = request.GET.get('q')
    product = Product.objects.filter(title__icontains=q)
    return render(request, 'products_list.html', context={'object_list': product})


def product_list_category(request, category_slug):
    category = Category.objects.filter(slug=category_slug).first()

    products = category.products.all()

    return render(request, 'home/include/cat_list.html', {'cat_list': products})

product/templates/product/detail1.html
{% load static %}
{% load widget_tweaks %}
{% load render_partial %}
<!DOCTYPE html>
<html lang="en">

<head>
    {% include 'home/include/head.html' %}
</head>

<body>
<!-- Topbar Start -->

{% include 'home/include/top_bar.html' %}

<!-- Topbar End -->


<!-- Navbar Start -->
{% render_partial 'product:navbar' %}
<!-- Navbar End -->


<!-- Breadcrumb Start -->
<div class="container-fluid">
    <div class="row px-xl-5">
        <div class="col-12">
            <nav class="breadcrumb bg-light mb-30">
                <a class="breadcrumb-item text-dark" href="#">Home</a>
                <a class="breadcrumb-item text-dark" href="#">Shop</a>
                <span class="breadcrumb-item active">Shop Detail</span>
            </nav>
        </div>
    </div>
</div>
<!-- Breadcrumb End -->


<!-- Shop Detail Start -->
<div class="container-fluid pb-5">
    <div class="row px-xl-5">
        <div id="product-carousel" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
                {% for image in product.images.all %}
                    <div class="carousel-item {% if forloop.first %}active{% endif %}">
                        <img class="d-block" style="max-width: 100%; height: auto;" src="{{ image.image.url }}"
                             alt="{{ product.title }}">
                    </div>
                {% endfor %}
            </div>
            <a class="carousel-control-prev" href="#product-carousel" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#product-carousel" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>

        <div class="col-lg-7 h-auto mb-30">
            <div class="h-100 bg-light p-30">
                <h3>{{ product.title }}</h3>
                <h3 class="font-weight-semi-bold mb-4">{{ product.price }}</h3>
                <p class="mb-4"> {{ product.description }}</p>
                <form action="{% url "cart:cart_add" product.id %}" method="post">
                    {% csrf_token %}
                    <div class="d-flex mb-3">
                        {% if product.size.all %}
                            <strong class="text-dark mr-3">Sizes:</strong>
                        {% endif %}
                        <div>
                            {% for size in product.size.all %}
                                <div class="custom-control custom-radio custom-control-inline">
                                    <input type="radio" class="custom-control-input" value="{{ size.title }}"
                                           id="{{ size.title }}"
                                           name="size">
                                    <label class="custom-control-label" for="{{ size.title }}">{{ size.title }}</label>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="d-flex mb-4">
                        {% if product.color.all %}
                            <strong class="text-dark mr-3">Colors:</strong>
                        {% endif %}
                        <div>
                            {% for color in product.color.all %}
                                <div class="custom-control custom-radio custom-control-inline">
                                    <input type="radio" class="custom-control-input" value="{{ color.title }}"
                                           id="{{ color.title }}" name="color">
                                    <label class="custom-control-label"
                                           for="{{ color.title }}">{{ color.title }}</label>
                                </div>
                            {% endfor %}
                        </div>
                    </div>

                    <div class="d-flex align-items-center mb-4 pt-2">
                        <div class="input-group quantity mr-3" style="width: 130px;">
                            <div class="input-group-btn">
                                <button class="btn btn-primary btn-minus" type="button">
                                    <i class="fa fa-minus"></i>
                                </button>
                            </div>
                            <input type="text" name="quantity" class="form-control bg-secondary border-0 text-center"
                                   value="1">
                            <div class="input-group-btn">
                                <button class="btn btn-primary btn-plus" type="button">
                                    <i class="fa fa-plus"></i>
                                </button>

                            </div>
                        </div>
                        <button class="btn btn-primary px-3"><i class="fa fa-shopping-cart mr-1"></i> Add To
                            Cart
                        </button>


                    </div>
                </form>
                <hr>
                {% if user.is_authenticated %}
                    {% if is_liked %}
                        <a href="{% url 'product:like' product.slug product.id %}" onclick="like()"
                           style="color: black;font-size: 25px;"><i
                                class="fa fa-heart" style="color:red;"></i> {{ product.likes.all.count }}</a>
                    {% else %}
                        <a href="{% url 'product:like' product.slug product.id %}" onclick="like()"
                           style="color: black;font-size: 25px;"><i
                                class="far fa-heart" style="color:red;"></i> {{ product.likes.all.count }}</a>

                    {% endif %}
                {% else %}
                    <a href="{% url 'account:user login' %}" style="color: black;font-size: 25px;"><i
                            class="far fa-heart" style="color:red;"></i> {{ product.likes.all.count }}</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>

</div>
<div class="row px-xl-5">
    <div class="col">
        <div class="bg-light p-30">
            <div class="nav nav-tabs mb-4">
                <a class="nav-item nav-link text-dark active" data-toggle="tab" href="#tab-pane-1">Description</a>
                <a class="nav-item nav-link text-dark" data-toggle="tab" href="#tab-pane-2">Information</a>
<a class="nav-item nav-link text-dark" data-toggle="tab" href="#tab-pane-3">Reviews ({{ product.get_comment_count }})</a>
            </div>
            <div class="tab-content">
                <div class="tab-pane fade show active" id="tab-pane-1">
                    <h4 class="mb-3">Product Description</h4>
                    <p>{{ product.description }}</p>
                </div>
                <div class="tab-pane fade" id="tab-pane-2">
                    <h4 class="mb-3">Additional Information</h4>
                    <p></p>
                    <div class="row">
                        {% for info in product.information.all %}
                            <div class="col-md-6">
                                <ul class="list-group list-group-flush">
                                    <li class="list-group list-group-item">
                                        {{ info.text }}
                                    </li>

                                </ul>
                            </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="tab-pane fade" id="tab-pane-3">
                    <div class="content">

                            {% for comment in product.comments.all %}
                                {% if comment.parent == None %}


                                        <div class="col-md-6">
                                            <h4 class="mb-4">{{ comment.product}}</h4>
                                            <div class="media mb-4">

                                                <div class="media-body">
                                                    <h6>{{ comment.user.get_username}}<small> - <i>{{ comment.created_at}}</i></small></h6>
                                                    <p>{{ comment.body}}</p>
                                                </div>
                                            </div>
                                        </div>
                                    <hr>

                                {% endif %}
                            {% endfor %}




                        <div class="col-md-6">
                            <h4 class="mb-4">Leave a review</h4>
                            <small>Your email address will not be published. Required fields are marked *</small>
                            <form>
                                <div class="form-group">
                                    <label for="message">Your Review *</label>
                                    <textarea id="message" cols="30" rows="5" class="form-control"></textarea>
                                </div>
                                <div class="form-group">
                                    <label for="name">Your Name *</label>
                                    <input type="text" class="form-control" id="name">
                                </div>
                                <div class="form-group">
                                    <label for="email">Your Email *</label>
                                    <input type="email" class="form-control" id="email">
                                </div>
                                <div class="form-group mb-0">
                                    <input type="submit" value="Leave Your Review" class="btn btn-primary px-3">
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
<!-- Shop Detail End -->


<!-- Products Start -->
{% render_partial 'product:Feature' %}
<!-- Products End -->


<!-- Footer Start -->
{% include 'home/include/footer.html' %}
<!-- Footer End -->


<!-- Back to Top -->
<a href="#" class="btn btn-success back-to-top"><i class="fa fa-angle-double-up"></i></a>


<!-- JavaScript Libraries -->
{% include 'home/include/js.html' %}
</body>
</html>